version: '3.9'

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node.js API Service
  api:
    build: .        # ✅ Build from current directory (where Dockerfile is)
    container_name: database-api
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    restart: always

volumes:
  mongo_data: {}
